CREATE TABLE mydb.points(
ID BIGINT NOT NULL AUTO_INCREMENT,
ADDRESS_ID BIGINT,
NAME VARCHAR (50),
PRIMARY KEY (ID),
FOREIGN KEY (ADDRESS_ID) REFERENCES addresses(ID)
);

INSERT INTO points (ADDRESS_ID, NAME) VALUES
(1,'Fora');

INSERT INTO points (ADDRESS_ID, NAME) VALUES
(6,'Metro');