CREATE TABLE mydb.products (
ID BIGINT NOT NULL AUTO_INCREMENT,
POINT_ID BIGINT,
PRICE DOUBLE ,
AMOUNT DOUBLE NOT NULL,
NAME  VARCHAR (50) NULL,
DESCRIPTION VARCHAR (255) NULL,
FOREIGN KEY (POINT_ID) REFERENCES points (ID),
PRIMARY KEY (ID)
);

INSERT INTO products (POINT_ID, PRICE, AMOUNT, NAME, DESCRIPTION) VALUES
(3, 800.00, 1.0, 'Bag', 'Accessories'),
(4, 350, 1.0, 'Ball', 'Sport goods'),
(5, 1500, 1.0, 'Bicycle', 'Sport goods');

INSERT INTO products (POINT_ID, PRICE, AMOUNT, NAME, DESCRIPTION) VALUES
(6,50.00, 1.0, 'Cup', 'Kitchen goods');
