CREATE TABLE mydb.users
(
  IS_BLOCK TINYINT,
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  ADDRESS_ID BIGINT,
  PASSWORD     VARCHAR(50),
  FIRST_NAME       VARCHAR(50),
  LAST_NAME   VARCHAR(50),
  EMAIL     VARCHAR(50),
  PHONE VARCHAR(13),
  LOGIN    VARCHAR(50),
  LAST_IP VARCHAR (50),
  REGISTER_DATA DATE,
  LAST_LOGIN_DATA DATE ,
  PRIMARY KEY (ID),
  FOREIGN KEY (ADDRESS_ID) REFERENCES addresses (ID)
);

INSERT INTO users (IS_BLOCK, ADDRESS_ID, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, PHONE, LOGIN, LAST_IP, REGISTER_DATA, LAST_LOGIN_DATA) VALUES
(3,4, 'password42', 'John', 'Ray', 'johmmail@i.ua', '+380635445436','joh5mmy_1234','137.100.0.0.1','2017.02.25', '2018.02.25');